[package]
name = "wordle"
version = "0.0.1"
edition = "2021"
authors = ["Nils Mathieu <nmathieu@student.42.fr>", "Margaux Riant <mriant@student.42.fr>"]

[profile.release]
opt-level=3

[workspace]
members = ["mlx"]

[dependencies]
mlx = { path = "mlx" }
libc = "0.2"